   main: com.tilundev.testingplugin.Main
   name: TestingPlugin
   version: 0.1
   author: TilunDev
   description: A Testing plugin for training purpose
   api-version: 1.15
   commands:
      kit:
         description: Give 64 Diamonds
         usage: /<command>
      apocalypse:
         description: Set the difficulty of you apocalypse
         usage: /<command>