   main: com.zomboplugin.Main
   name: ZomboPlugin
   version: 0.2
   author: TilunDev and Anidli
   description: A Testing plugin for training purpose
   api-version: 1.15
   commands:
      ZP_kit:
         description: Give 64 Diamonds
         usage: /<command>
      ZP_apocalypse:
         description: Set the difficulty of you apocalypse
         usage: /<command>
      ZP_safezone_add:
         description: Add new safezone on your current location, need radius to be specified
         usage: /<command>