   main: com.zomboplugin.Main
   name: TestingPlugin
   version: 0.1
   author: TilunDev
   description: A Testing plugin for training purpose
   api-version: 1.15
   commands:
      kit:
         description: Give 64 Diamonds
         usage: /<command>