   main: com.zomboplugin.Main
   name: ZomboPlugin
   version: 0.2
   author: TilunDev and Anidli
   description: A Testing plugin for training purpose
   api-version: 1.15
   commands:
      kit:
         description: Give 64 Diamonds
         usage: /<command>
      apocalypse:
         description: Set the difficulty of you apocalypse
         usage: /<command>